version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public:/latrobe/public
    depends_on:
      - php
    restart: always
  php:
    build: 
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./public:/latrobe/public
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'latrobe'
      MYSQL_USER: 'latrobe'
      MYSQL_PASSWORD: 'password'
    volumes:
      - latrobe:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
volumes:
  latrobe: {}